### ISSUE TITLE
Can not run this UI application on Azure Web App

### ISSUE THREAD

**Issue by artus** [Microsoft/ConversationLearner-SDK#326]
I can't seem to make the UI application run on an Azure Web App. I don't know how to configure iss using `web.config` to work with `startUiServer()`.

Could anyone please point me in the right direction? I lost 3 days trying multiple methods.

**Comment by LarsLiden** [comment]
Have you taken a look at the "Publishing your Bot" section in the [Readme](https://github.com/Microsoft/ConversationLearner-Samples/blob/master/README.md)?

**Comment by artus** [comment]
I think those are for publishing your bot. I want to put the UI application online so that I can showcase training a bot from anywhere.

**Comment by LarsLiden** [comment]
Ah, I misunderstood.  We currently do not support the UI running in a Web App.  There isn't any authentication for the UI, so anyone hitting the browser could edit your bot.  We may add a hosted version or distribute as an electron app in the future, but not high priority at the moment.   Best way to showcase at the moment would be to bring a laptop with the UI installed.
