### ISSUE TITLE
Error scoring an action with a label greater than 30

### ISSUE THREAD

**Issue by kolibri26** [Microsoft/ConversationLearner-SDK#342]
We are working with an label entity with a GUID format that have more than 30 characters and when we scrore the action, we found the following error:

![error max chars entity](https://user-images.githubusercontent.com/1760696/46606804-e6f32b00-cafe-11e8-901d-dd3b65c2a4ac.png)

Can this error a bug or a limitation of the Train Dialog?

**Comment by LarsLiden** [comment]
@kolibri26 - we can increase the character limit.  Will take a day or two to get it pushed out.   Thanks!

**Comment by msft-shahins** [comment]
@kolibri26 - This issue should have been resolved now. The limit have been increased to 50 characters.
